version: '3.8'
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'PersonDemo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'demouser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: 'demouser'
      MYSQL_PASSWORD: 'password'
    ports:
      - "8081:80"
    depends_on:
      - db

# Names our volume
volumes:
  my-db:
    driver: local
